module.exports = [
  {
    'id': '0',
    'first_name': 'Alexandre',
    'last_name': 'Houmeau',
    'email': 'alexandre@gmail.com',
    'password': '123456789',
    'gender': 'male',
    'height': 1.93,
    'weight': 98,
    'city': 'Paris',
    'cityCode': 75000,
    'street_number': 13,
    'street_type': 'rue',
    'street_name': 'de canobrai',
    'phone': '0651448017',
    'image_profil':
      'https://img.maxisciences.com/article/480/mourir-moins-con/le-plus-rapide-sur-terre-c-est-de-notoriete-publique-le-guepard-est-l-animal-terrestre-le-plus-rapide-au-monde-il-peut-courir-jusqu-a-une-vitesse-de-112-km-h_4b614450da0e0da63cbf951da96d092feb29bcdf.jpg'
  },
  {
    'id': '1',
    'first_name': 'Hari',
    'last_name': 'Tharmalingam',
    'email': 'hari@gmail.com',
    'password': '123456789',
    'gender': 'male',
    'height': 1.75,
    'weight': 60,
    'city': 'Paris',
    'cityCode': 75000,
    'street_number': 14,
    'street_type': 'rue',
    'street_name': 'de canape',
    'phone': '0651448017',
    'image_profil':
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'
  },
  {
    'id': '2',
    'first_name': 'Corentin',
    'last_name': 'Rativeau',
    'email': 'corentin@gmail.com',
    'password': 'sqkldjqls',
    'gender': 'male',
    'height': 1.85,
    'weight': 61,
    'city': 'Paris',
    'cityCode': 75000,
    'street_number': 10,
    'street_type': 'rue',
    'street_name': 'de madame',
    'phone': '0651448017',
    'image_profil':
      'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
  },
  {
    'id': '3',
    'first_name': 'Gabriel',
    'last_name': 'Rativeau',
    'email': 'gab75000@gmail.com',
    'password': 'sihqdiuqsdh',
    'gender': 'male',
    'height': 1.80,
    'weight': 51,
    'city': 'Paris',
    'cityCode': 75000,
    'street_number': 1023,
    'street_type': 'impasse',
    'street_name': 'balisto',
    'phone': '0651448017',
    'image_profil':
      'https://s.abcnews.com/images/US/gun_face_180622_hpMain_4x3_992.jpg'
  },
  {
    'id': '4',
    'first_name': 'Professeur',
    'last_name': 'Chen',
    'email': 'chenProf@gmail.com',
    'password': 'sasha',
    'gender': 'male',
    'height': 1.50,
    'weight': 31,
    'city': 'Bourg Pallette',
    'cityCode': 30983,
    'street_number': 23,
    'street_type': 'rue',
    'street_name': 'de la street',
    'phone': '9879878',
    'image_profil':
      'https://www.pokepedia.fr/images/thumb/3/39/Roucool_du_Professeur_Chen.png/200px-Roucool_du_Professeur_Chen.png'
  },
  {
    'id': '5',
    'first_name': 'Cyril',
    'last_name': 'Vimard',
    'email': 'cvm@gmail.com',
    'password': '908098098',
    'gender': 'male',
    'height': 1.90,
    'weight': 51,
    'city': 'Paris',
    'cityCode': 75000,
    'street_number': 40,
    'street_type': 'rue',
    'street_name': 'de Paris',
    'phone': '0897867564',
    'image_profil':
      'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
  },
  {
    'id': '6',
    'first_name': 'Clara',
    'last_name': 'Marchand',
    'email': 'clara@gmail.com',
    'password': 'motdepasse',
    'gender': 'female',
    'height': 1.53,
    'weight': 51,
    'city': 'Paris',
    'cityCode': 75000,
    'street_number': 23,
    'street_type': 'rue',
    'street_name': 'de la Tour Auver',
    'phone': '098987876',
    'image_profil':
      'https://images.unsplash.com/photo-1542080681-b52d382432af?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80'
  },
  {
    'id': '7',
    'first_name': 'Nathalie',
    'last_name': 'Duplentier',
    'email': 'nath33@gmail.com',
    'password': 'password',
    'gender': 'female',
    'height': 1.53,
    'weight': 300,
    'city': 'Bordeaux',
    'cityCode': 3300,
    'street_number': 201,
    'street_type': 'boulevard',
    'street_name': 'Henry Martin',
    'phone': '123451426',
    'image_profil':
      'https://storage-dating.euranka.com/uploads/sites/5/2018/12/photo-profil-rencontre-2019.jpg'
  },
  {
    'id': '8',
    'first_name': 'Maxime',
    'last_name': 'Lemaitre',
    'email': 'maxime.lemaitre@gmail.com',
    'password': 'papillionDeNuit3232',
    'gender': 'male',
    'height': 1.76,
    'weight': 80,
    'city': 'Paris',
    'cityCode': 75009,
    'street_number': 2,
    'street_type': 'rue',
    'street_name': 'des Martyrs',
    'phone': '0651446728',
    'image_profil':
      'https://i.pinimg.com/236x/f3/84/1c/f3841c8db2b59bb0a6393ec167868b6f.jpg'
  },
  {
    'id': '9',
    'first_name': 'Marine',
    'last_name': 'Belot',
    'email': 'marine.belot@gmail.com',
    'password': 'papillionDeJour2323',
    'gender': 'female',
    'height': 1.64,
    'weight': 56,
    'city': 'Paris',
    'cityCode': 75009,
    'street_number': 2,
    'street_type': 'rue',
    'street_name': 'des Martyrs',
    'phone': '0642315609',
    'image_profil':
      'https://i.pinimg.com/236x/57/b0/01/57b0013ab8264667f6530ec352291353.jpg'
  },
  {
    'id': '10',
    'first_name': 'Charlotte',
    'last_name': 'Machin',
    'email': 'char-mach@gmail.com',
    'password': 'ceciestunmotdepass',
    'gender': 'female',
    'height': 1.45,
    'weight': 25,
    'city': 'Paris',
    'cityCode': 75009,
    'street_number': 56,
    'street_type': 'avenue',
    'street_name': 'Charles de Gaule',
    'phone': '0728523423',
    'image_profil':
      'https://www.gabrielgorgi.com/wp-content/uploads/2019/12/01.jpg.webp'
  }
]
